on:
  push:
    branches:
      - main
    paths-ignore: # dont run when changes made to these folders
      - ".vscode/**"
      - CHANGELOG.md
    tags:
      - v*.*.*

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: clean install dependencies
        run: npm ci

      - name: Run tests (Linux)
        run: xvfb-run -a npm test
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Run tests (Windows/Mac)
        run: npm test
        if: ${{ matrix.os != 'ubuntu-latest' }}

      - name: Publish to VSCode marketplace
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npx vsce publish ${TAG_NAME#v}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          TAG_NAME: ${{ github.ref.name }}

      - name: GitHub Release
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
